# Kiarash Geraili, Computer Science student at AmirKabir University of Technology
# Second Section: Numpy 
# Based on a Data Mining Course By Adel Mohammadpour
# Teaching Assistant: Vahid Mahzoon¶


In [1]:
#NumPy is a fundamental package for scientific computing with Python
#many other powerful packages in python like scikit-learn use numpy

In [1]:
import numpy as np

#finding version of your numpy
np.__version__

'1.18.1'

In [6]:
!pip install update numpy

#cheking for any updates for numpy library

# Arrays

In [8]:
l0 = [1,2,3,4]

#Creat a vector
np.array(l0)

array([1, 2, 3, 4])

In [9]:
#create a matrix

matrix = [l0 , [5,6,7,8] , [9,10,11,12]]
np.array(matrix)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
#Difference between lists and arrays are the functions that you can perform on them like for example when you want to divide an array by 4, the result will be printed on request but in case of a list, Python will throw an error message.
#but you should notice that working with Numpy arrays is much more faster than working with Python Lists

In [5]:
array = np.array([1,13,17,9], dtype = 'int32')
array

array([ 1, 13, 17,  9])

In [6]:
array = np.array([1,13,'Kiarash Ger',9], dtype = 'int32')
#when you assign a value to dtype like int32, all the elements of the array should get int32 value

ValueError: invalid literal for int() with base 10: 'Kiarash Ger'

In [8]:
import sys

List = [1,2,3,4]
Array = np.array([1,2,3,4])

SizeList = sys.getsizeof(1)*len(List)
SizeArray = Array.itemsize*Array.size
#Comparing size of a python built-in List to a numpy array to find out another reason that why numpy array is much more faster

print('Size of the List is: ' + str(SizeList)) 
print('Size of the Array is: ' + str(SizeArray))

Size of the List is: 112
Size of the Array is: 16


In [19]:
#In numerical analysis and scientific computing, a sparse matrix or sparse array is a matrix in which most of the elements are zero.
#By contrast, if most of the elements are nonzero, then the matrix is considered dense.
#we can create a sparse matrix using the Scipy library. As we will talk about this library later we gene

Sparse = np.array([[0,0,31,0],[0,2,0,0],[0,0,0,0],[4,0,0,1.1]])
Sparse

array([[ 0. ,  0. , 31. ,  0. ],
       [ 0. ,  2. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ],
       [ 4. ,  0. ,  0. ,  1.1]])

In [21]:
#using np.count_nonzero you can find how many elements of your np.array are not equal to zero
#using np.nonzero method you can find indexes of the non zero elements in a np.array
CountNonZero = np.count_nonzero(Sparse)
Ind_NonZero = np.nonzero(Sparse)

print(CountNonZero)

print(Ind_NonZero)
#first array in Ind_NonZero illustrate indexes of rows, in which have non-zero elements
#second array in Ind_NonZero illustrate indexes of elements of the rows in which have non-zero elements

4
(array([0, 1, 3, 3], dtype=int64), array([2, 1, 0, 3], dtype=int64))


# arange(), linspace() 

In [24]:
#arange() is an inbuilt NumPy function that returns an array object containing evenly spaced values within the given range.  
#arange(start, stop, step) function returns all values within a given interval(start,stop) by a step.
#create all the numbers between 1 to 10 with a 0.5 step 
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [60]:
# np.arange(x)  is one of the array creation routines based on numerical ranges. It creates an instance of ndarray with evenly spaced values and returns the reference to it.

np.arange(20.8)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.])

In [32]:
#linspace(start,stop,x) Returns x items in an interval(start, stop) with a same specific distance between each other.

np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [33]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# zeros(), ones(), eye(), random.rand()

In [25]:
#numpy.zeros(shape, dtype = None, order = ‘C’) : Return a new array of given shape and type, with zeros.

np.zeros(3)

array([0., 0., 0.])

In [28]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [29]:
#ones.zeros(shape, dtype = None, order = ‘C’) : Return a new array of given shape and type, with ones.

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
# eye builds an identity matrix or a unit matrix

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
# Numpy also has random functions. using np.random.rand() we can create random matrixes and random vectors
# notice that as we saw in the last section, as random library, np.random also create matrixes with elements between (0,1)

vector = np.random.rand(4)
matrix = np.random.rand(3,2)

vector

array([0.08373431, 0.82586723, 0.60595356, 0.67963056])

In [39]:
matrix

array([[0.39275142, 0.49397865],
       [0.75206079, 0.30257098],
       [0.10173377, 0.2172576 ]])

In [41]:
# creat a random integer in an interval(x,y)

np.random.randint(20,60)

35

In [46]:
# create a vector with random elements belong to an interval like (34,73)

np.random.randint(34,73,3)

array([50, 44, 46])

In [49]:
# create a matrix with random elements belong to an interval like (17,23)

np.random.randint(17,23,(4,5))

array([[17, 18, 18, 17, 21],
       [17, 19, 20, 22, 22],
       [17, 22, 22, 22, 20],
       [19, 19, 22, 17, 20]])

# Shape and Reshape 

In [64]:
asc_array = np.arange(50)
asc_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [65]:
asc_array.shape
#this function shows us the shape of the array

(50,)

In [76]:
#for reshaping an array(or a matrix) to a matrix we can use reshape(x,y) in which x,y are rows and columns for our final matrix
#for example, we want to create and reshape a 20*1 array into a 5*4 matrix and reshape a 5*4 matrix to a 10*2 matrix: follow next 3 Input and output codes

Array20_1 = np.random.randint(0,100,20)
Array20_1

array([79, 80, 42, 86, 46, 94, 32, 34, 37, 18, 92, 48, 95, 72, 78, 19, 35,
       65,  5, 21])

In [78]:
Array5_4 = Array20_1.reshape(5,4)
Array5_4

array([[79, 80, 42, 86],
       [46, 94, 32, 34],
       [37, 18, 92, 48],
       [95, 72, 78, 19],
       [35, 65,  5, 21]])

In [79]:
Array10_2 = Array5_4.reshape(10,2)
Array10_2

array([[79, 80],
       [42, 86],
       [46, 94],
       [32, 34],
       [37, 18],
       [92, 48],
       [95, 72],
       [78, 19],
       [35, 65],
       [ 5, 21]])

# Min, Max, Argmin, Argmax

In [87]:
Matrix = np.random.randint(1,100,(3,4))
Matrix

array([[41, 23, 42, 32],
       [91, 78, 37, 96],
       [56, 79,  9, 32]])

In [88]:
# assume that you want to find the maximum and minimum and their indexes in your matrix:

print('Maximum is: ' + str(Matrix.max()) + ' With index of: ' + str(Matrix.argmax()))
print('Minimum is: ' + str(Matrix.min()) + ' With index of: ' + str(Matrix.argmin()))

Maximum is: 96 With index of: 7
Minimum is: 9 With index of: 10


# Arithmetic

In [89]:
#we can add a vector or a matrix to another one like this:

Matrix0 = np.random.randint(0,100,(3,4))
Matrix1 = np.random.randint(0,100,(3,4))
Matrix0

array([[52, 71, 21, 62],
       [30, 46, 63, 35],
       [34,  4, 84, 14]])

In [90]:
Matrix1

array([[38, 61, 90, 25],
       [77, 95, 36, 21],
       [99, 60, 50, 21]])

In [91]:
Matrix0 + Matrix1

array([[ 90, 132, 111,  87],
       [107, 141,  99,  56],
       [133,  64, 134,  35]])

In [92]:
#we can add (or deivide or multiply or subtract)a constat number to all elements of an array

Matrix0 + 1.5

array([[53.5, 72.5, 22.5, 63.5],
       [31.5, 47.5, 64.5, 36.5],
       [35.5,  5.5, 85.5, 15.5]])

In [93]:
Matrix0 - 15

array([[ 37,  56,   6,  47],
       [ 15,  31,  48,  20],
       [ 19, -11,  69,  -1]])

In [97]:
(Matrix0/3)*2

array([[34.66666667, 47.33333333, 14.        , 41.33333333],
       [20.        , 30.66666667, 42.        , 23.33333333],
       [22.66666667,  2.66666667, 56.        ,  9.33333333]])

In [98]:
Matrix1/Matrix0

array([[ 0.73076923,  0.85915493,  4.28571429,  0.40322581],
       [ 2.56666667,  2.06521739,  0.57142857,  0.6       ],
       [ 2.91176471, 15.        ,  0.5952381 ,  1.5       ]])

In [99]:
1/Matrix0

array([[0.01923077, 0.01408451, 0.04761905, 0.01612903],
       [0.03333333, 0.02173913, 0.01587302, 0.02857143],
       [0.02941176, 0.25      , 0.01190476, 0.07142857]])

In [2]:
#if we have a element resulted in a division by a zero in a matrix or vector, pyhton type the result with a notification:

vector = np.array([0,2,3,1,5])
vector/vector

C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


array([nan,  1.,  1.,  1.,  1.])

In [3]:
# when we multipy a vector to another one, pyhton multipies element to element and results in another vector
# so the result of a normal multiplication is not an inner product:

vector*vector

array([ 0,  4,  9,  1, 25])

In [4]:
#we can use operator @ for inner product 
vector @ vector

39

In [15]:
A = np.random.randint(0,100,(3,4))
B = np.random.randint(0,100,(4,2))

print('Matrix A is: ')
print(A)
print('Matrix B is: ')
print(B)
print()
print('A.B is:')
print(A @ B)

Matrix A is: 
[[40 86 70 97]
 [68 74 67 31]
 [10 32 55 99]]
Matrix B is: 
[[41 24]
 [43 55]
 [54 56]
 [82 30]]

A.B is:
[[17072 12520]
 [12130 10384]
 [12874  8050]]


In [7]:
vector

array([0, 2, 3, 1, 5])

In [10]:
#np.sqrt() Return the non-negative square-root of an array, element-wise.

np.sqrt(vector)

array([0.        , 1.41421356, 1.73205081, 1.        , 2.23606798])

In [16]:
#np.exp Calculate the exponential of all elements in the input array.

np.exp(vector)

array([  1.        ,   7.3890561 ,  20.08553692,   2.71828183,
       148.4131591 ])

In [18]:
np.sin(vector)@ np.cos(vector)

-0.335470838785271

In [20]:
#the natural logarithm log is the inverse of the exponential function, so that log(exp(x)) = x. The natural logarithm is logarithm in base e.

np.log(vector)

C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


array([      -inf, 0.69314718, 1.09861229, 0.        , 1.60943791])

In [21]:
#returns the summation of all the elements in an array

np.sum(vector)

11

In [31]:
#finding out statistical parameters easily using numpy

Matrix = np.random.randint(0,100,(5,5))

print('For matrix: ',Matrix)
print('The Mean of all elements in Matrix is: ',np.mean(Matrix))
print('The Median of all elements in Matrix is: ',np.median(Matrix))

For matrix:  [[96 49 70 76 43]
 [86 84  1 35 64]
 [46 12 89 83 68]
 [14 64 50 23 27]
 [30 99 90 79 23]]
The Mean of all elements in Matrix is:  56.04
The Median of all elements in Matrix is:  64.0


In [33]:
Matrix = np.random.randint(0,20,(6,6))
Matrix

array([[ 5, 10,  8, 13, 12,  9],
       [ 5,  8,  7,  6, 11, 10],
       [11, 18,  9,  4, 16,  0],
       [ 7,  3, 15,  6, 17,  7],
       [14, 15,  9, 18, 10, 11],
       [ 8, 18,  1, 19, 19, 10]])

In [37]:
#find the unique elements of an array and returns the sorted unique elements of an array. 

np.unique(Matrix)

array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

# Indexing

In [39]:
#there are some similarities between array indexing and list indexing:

arr = np.random.rand(10)
arr

array([0.71814042, 0.25696016, 0.65416495, 0.38244192, 0.42149954,
       0.12989872, 0.65709187, 0.57207581, 0.38404566, 0.80750162])

In [42]:
arr[0],arr[3]

(0.7181404235630507, 0.3824419171873994)

In [43]:
arr[2:7]

array([0.65416495, 0.38244192, 0.42149954, 0.12989872, 0.65709187])

In [46]:
arr[2:]

array([0.65416495, 0.38244192, 0.42149954, 0.12989872, 0.65709187,
       0.57207581, 0.38404566, 0.80750162])

In [45]:
arr[:3]

array([0.71814042, 0.25696016, 0.65416495])

In [52]:
Matrix = np.random.randint(0,3,(4,4))
Matrix

array([[0, 2, 1, 1],
       [1, 0, 2, 2],
       [0, 1, 1, 1],
       [0, 0, 0, 2]])

In [53]:
Matrix[:2]

array([[0, 2, 1, 1],
       [1, 0, 2, 2]])

In [55]:
Matrix[2:]

array([[0, 1, 1, 1],
       [0, 0, 0, 2]])

In [56]:
Matrix[1][2]

2

In [59]:
Matrix[1,2]

2

In [60]:
Matrix

array([[0, 2, 1, 1],
       [1, 0, 2, 2],
       [0, 1, 1, 1],
       [0, 0, 0, 2]])

In [62]:
Matrix[:2] = 999
Matrix

array([[999, 999, 999, 999],
       [999, 999, 999, 999],
       [  0,   1,   1,   1],
       [  0,   0,   0,   2]])

In [70]:
MatrixSlice = Matrix[2:]
MatrixSlice

#sepraring a part of an array

array([[0, 1, 1, 1],
       [0, 0, 0, 2]])

In [71]:
MatrixSlice[:] = 10
MatrixSlice

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [72]:
Matrix

#as you can see there is a problem because as we changed the slice
#the whole matrix changed, which could make us wrong in many cases

array([[999, 999, 999, 999],
       [999, 999, 999, 999],
       [ 10,  10,  10,  10],
       [ 10,  10,  10,  10]])

In [77]:
#in order to avoid that problem we use copy() method

MatrixCopy = Matrix.copy()
MatrixCopy[:] = 4500
print(MatrixCopy)
print(Matrix)

[[4500 4500 4500 4500]
 [4500 4500 4500 4500]
 [4500 4500 4500 4500]
 [4500 4500 4500 4500]]
[[999 999 999 999]
 [999 999 999 999]
 [ 10  10  10  10]
 [ 10  10  10  10]]


# Broadcasting

In [82]:
vector = np.random.rand(3)
print('vector is:')
print(vector)

print()

matrix = np.random.randint(0,10,(3,3))
print('matrix is:')
print(matrix)

vector is:
[0.74153936 0.67160432 0.23527974]

matrix is:
[[2 4 5]
 [2 3 0]
 [3 5 1]]


In [83]:
matrix + vector
#it seems that if we want to add a vector to a matrix but in pyhton if you do such thing, 
#Pyhon will change the vector to a matrix by producing same rows as the matrix has, and then adds the vector to all rows of the matrix

array([[2.74153936, 4.67160432, 5.23527974],
       [2.74153936, 3.67160432, 0.23527974],
       [3.74153936, 5.67160432, 1.23527974]])

In [85]:
# if you remmeber, when we added a number to a vector the same happened (all the element of the vector increased by the same number that we added)

vector + 2
# in another word, pyhton changes the single number into a vector and add it to the first vector

array([2.74153936, 2.67160432, 2.23527974])

# Selection

In [88]:
matrix

array([[2, 4, 5],
       [2, 3, 0],
       [3, 5, 1]])

In [89]:
matrix > 2

#check the condition for all elements and returns an array of booleans for each element

array([[False,  True,  True],
       [False,  True, False],
       [ True,  True, False]])

In [92]:
#for finding elements using a condition we should use an array:

Conditional_Elements = matrix[matrix > 2]
Conditional_Elements

array([4, 5, 3, 3, 5])

# Polynomial

In [93]:
#assume that we want to create a polynomial using coefficionts:

coeff = np.array([2,1,0,1])
#2x^3 + x^2 + 1

np.polyval(coeff, 3)
#np.polyval(x ,y) create a polynomial using x coefficinets and calculates the polynomial using y value
#for example in this section it returnes 2(3)^3 + (3)^2 + 1

64

In [95]:
np.polyder(coeff)

# Returns the derivative of the specified order of a polynomial using coefficients

array([6, 2, 0])

In [97]:
np.polyval(np.polyder(coeff) ,2)

#result of the derivative polynomial for x = 2

28

In [99]:
np.polyint(coeff)

#Return an antiderivative (indefinite integral) of a polynomial.

array([0.5       , 0.33333333, 0.        , 1.        , 0.        ])

In [102]:
np.polyval(np.polyint(coeff) ,1)

#result of the integral polynomial for x = 1

1.8333333333333333

In [104]:
coeff = np.array([1,0,-1])

#Return the roots of a polynomial with coefficients given in
np.roots(coeff)

array([ 1., -1.])

In [109]:
# so if we want to find the maximom or minimum of a polynomial, one way is to find the root of devariation function 

coeff = np.array([1,-2,1])
np.roots(np.polyder(coeff))

# for example we trivially know that (x - 1)^2 has a global minimum of 1

array([1.])